// <auto-generated />
namespace SuperSecret.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tilbakeTilOrginalBruker : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tilbakeTilOrginalBruker));
        
        string IMigrationMetadata.Id
        {
            get { return "201503231316432_tilbakeTilOrginalBruker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
